# -*- coding: utf-8 -*-
"""Anton and Letters-443A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oc6sOFujaB1eINrOMC45mwJFRjjc8M2N
"""

def letters(s, c):
  s = sorted(s)
  for i in range(len(s)):
    if ord(s[i]) >= 97 and ord(s[i]) <= 122:
      c += 1

      if ord(s[i]) == ord(s[i+1]):
        c -= 1
  return c

s = input()
count = 0
print(letters(s, count))



