# -*- coding: utf-8 -*-
"""Anton and Danik-734A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oc6sOFujaB1eINrOMC45mwJFRjjc8M2N
"""

n = int(input())
s = input()
countA = 0
countD = 0

for i in range(len(s)):
  if s[i] == 'A':
    countA += 1
  else:
    countD += 1
    continue
    
if countA > countD:
  print('Anton')
    
elif countA == countD:
  print('Friendship')
    
else:
  print('Danik')

