# -*- coding: utf-8 -*-
"""Football_96A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x0uRY_pbsa2dDc_D2JnArGcsU4-uTguh

**FOOTBALL 96A**
"""

def football(s, c, max_c):  

  for i in range(len(s)-1):
    if s[i] == s[i+1]:
      c += 1
      print(c)
    else:
      max_c = max(c, max_c)
      c = 1
    if max_c >= 7:
      break
  print(max_c, c)
  if max_c >= 7:
    print('YES')
  else:
    print('NO')

s = input().strip()
count = 1
max_count = 0

football(s, count, max_count)



