# -*- coding: utf-8 -*-
"""HQ9+-133A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oc6sOFujaB1eINrOMC45mwJFRjjc8M2N
"""

s = input()

if 'H' in s or 'Q' in s or '9' in s:
  print("YES")
else:
  print("NO")

