# -*- coding: utf-8 -*-
"""Required_Remainder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cL-xIjVcvEkMS7rjnvO-Rj4wu6jSOrD4
"""

testcase = int(input())

for i in range(testcase):
  x, y, n = map(int, input().split())

  count = n//x
  answer = x * count + y

  if answer > n:
    answer -= x

  print(answer)