# -*- coding: utf-8 -*-
"""young_physicist_69A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x0uRY_pbsa2dDc_D2JnArGcsU4-uTguh

**FOOTBALL 96A**
"""

def young_physicist(row, c1_sum, c2_sum, c3_sum):

  for i in range(0, row):
    c1,c2,c3 = list(map(int, input().split()))

    c1_sum += c1
    c2_sum += c2
    c3_sum += c3
  
  if c1_sum == 0 and c2_sum == 0 and c3_sum == 0:
    print('YES')
  else:
    print("NO")

n = int(input())
x_sum = 0
y_sum = 0
z_sum = 0

young_physicist(n, x_sum, y_sum, z_sum)

